---
title: "Kid AoA experiment analysis"
author: "Ashley Leung, Ben Morris, and Dan Yurovsky"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: hide
---

```{r load-libraries, warning = F, message = F}
library(here)
library(knitr)
library(janitor)
library(ggthemes)
library(tidyverse)
library(ggrepel)
library(lme4)
library(lmerTest)
library(broom)
library(broom.mixed)
library(tidyboot)
library(ggthemes)
library(effectsize)
library(papaja)
library(glue)

theme_set(theme_few(base_size = 14))

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)
```

```{r load-data,, warning = F, message = F}
#adjust this total n to grab all the participants data below
n <- 19

items <- c("ball", "artichoke", "cat", "dog", "duck", "elephant", "gorilla", 
           "leopard", "lobster", "owl", "pig", "raccoon", "turtle", "zebra", 
           "snake", "fish", "penguin", "car", "stairs")

mutated_items <- map(items, ~c(glue("{.x}_yes"), glue("{.x}_no"))) %>%
  unlist()


# kid data
tmp <- read_csv(here("kid_data/kid_qualtrics_raw_final.csv")) %>%
  slice(2:n()) %>%
  filter(Finished == "True") %>%
  select(-EndDate:-UserLanguage) %>%
  filter(!is.na(Q60)) %>%
  rename(age = Q59, gender = Q60, db_id = ID, exclude = Q61) %>%
  filter(is.na(exclude)) %>%
  select(db_id, age, gender, all_of(mutated_items), Why) %>%
  mutate(id = row_number()) 

data <- tmp %>%
  select(-Why) %>%
  pivot_longer(cols = all_of(mutated_items), names_to = "item", 
               values_to = "judgment") %>%
  rowwise() %>%
  mutate(item = str_split(item, "_",simplify = TRUE)[1]) %>%
  group_by(age, gender, db_id, id, item) %>%
  mutate(judgment = as.numeric(judgment)) %>%
  summarise(judgment = mean(judgment, na.rm = TRUE))

word_data <- data %>%
  filter(!item %in% c("artichoke", "ball", "car", "stairs")) %>%
  rename(word = item)

practice_data <- data %>%
  filter(item %in% c("artichoke", "ball", "car", "stairs")) %>%
  rename(word = item) %>%
  filter(!is.na(judgment))

kuperman_aoas <- read_csv(here("corpus_data/kuperman_aoas.csv"))
```

```{r}
#adult comparison data
adult_tmp <- read_csv(here("adult_data/aoa_adult_raw_1.15.2021.csv")) %>%
  slice(2:n()) %>%
  filter(Finished == "True") %>%
  select(-StartDate:-UserLanguage) %>%
  filter(attn_check == 15) %>%
  select(all_of(items), Why) %>%
  mutate(id = row_number())

adult_data <- adult_tmp[-1:-6,] %>%
  select(-Why) %>%
  pivot_longer(cols = all_of(items), names_to = "item", 
               values_to = "judgment") %>%
  rowwise() %>%
  mutate(item = str_split(item, "_",simplify = TRUE)[1]) %>%
  group_by(id, item) %>%
  mutate(judgment = as.numeric(judgment)) %>%
  summarise(judgment = mean(judgment, na.rm = TRUE)) %>%
  mutate(age = "adult")

adult_word_data <- adult_data %>%
  filter(!item %in% c("artichoke", "ball", "car", "stairs")) %>%
  rename(word = item)

adult_practice_data <- adult_data %>%
  filter(item %in% c("artichoke", "ball", "car", "stairs")) %>%
  rename(word = item) %>%
  filter(!is.na(judgment))

kuperman_aoas <- read_csv(here("corpus_data/kuperman_aoas.csv"))
```


```{r}
#to drop for not answering every question
toDrop <- data %>% 
  filter(is.na(judgment)) %>%
  distinct(db_id, id, age)

toDrop

#remaining subs to collect
data %>% distinct(age, id) %>% ungroup() %>% 
  filter(!id %in% (toDrop %>% pull(id))) %>%
  count(age) %>%
  mutate(remaining = 12 - n)

```


```{r plot-pilot-data}
joined_data <- word_data %>%
  filter(!id %in% (toDrop %>% pull(id))) %>%
  bind_rows(adult_word_data) %>%
  left_join(kuperman_aoas, by = "word")
```

```{r}
# explanations
explanations <- tmp %>% 
  filter(!id %in% (toDrop %>% pull(id))) %>%
  select(id, db_id, Why) %>%
  sample_n(nrow(.))
```


# Overall Effect

```{r overall}
data_overall <- joined_data %>% 
  # only kids
  filter(age != "adult") %>%
  group_by(word, aoa) %>%
  summarize(judgment = mean(judgment, na.rm = T))

#use the raw data to make line and variability
   #points show averages
ggplot(joined_data, aes(x = aoa, y = judgment,
                      label = word)) + 
  # geom_jitter() +
  geom_smooth(method = "lm") +
  geom_label_repel(data = data_overall) +
  xlab("Adult AoA estimates (Kuperman)") +
  ylab("Kid Judgments") +
  scale_y_continuous(breaks = c(1:6), limit = c(1,6))
```

```{r}
lm(judgment ~ aoa, data = joined_data) %>%
  summary()

joined_data %>%
  group_by(word) %>%
  summarise(mean = mean(judgment),
            sd = sd(judgment),
            n = n())
```

# Averages by age

```{r, fig.height = 6, fig.width = 9}
data_by_age <- joined_data %>% 
  mutate(word = substr(word, 0, 3)) %>%
  group_by(age, word, aoa) %>%
  summarize(judgment = mean(judgment, na.rm=T))

#use the raw data to make line and variability
   #points show averages by age
ggplot(joined_data, aes(x = aoa, y = judgment, group = age,
                      label = word)) + 
  # # if we want to add raw data
  # geom_jitter(color = "grey" , alpha = .5) +
  geom_smooth(method = "lm") +
  geom_point(data = data_by_age) +
  # a bit hard to see on this plot if we use labels, suggest we use regular points instead
  # geom_label_repel(data = data_by_age, point.padding = 0, 
        # label.padding = .15, label.size = .1) +
  facet_grid(.~age) + 
  xlab("Adult AoA estimates (Kuperman)") +
  ylab("Kid Judgments") +
  coord_cartesian(ylim = c(0,7)) +
  scale_y_continuous(breaks = c(1:6))
```


# vs. adult judgements, not Kuperman

```{r}
# split half adult data
training_adults <- adult_word_data %>% distinct(id) %>% pull(.) %>% sample(length(.)/2)
testing_adults <- adult_word_data %>% distinct(id) %>% filter(!id %in% training_adults) %>% pull(id)

adult_avg <- adult_word_data %>%
  filter(id %in% training_adults) %>%
  group_by(word) %>%
  summarize(adult_judgment = mean(judgment))

joined_adult_wide <- joined_data %>%
  left_join(adult_avg) %>%
  filter(! (id %in% training_adults & age == "adult"))

data_by_age <- joined_adult_wide %>% 
  mutate(word = substr(word, 0, 3)) %>%
  group_by(age, word, aoa, adult_judgment) %>%
  summarize(judgment = mean(judgment, na.rm=T))

#use the raw data to make line and variability
   #points show averages by age
ggplot(joined_adult_wide, aes(x = adult_judgment, y = judgment, group = age,
                      label = word)) + 
  # # if we want to add raw data
  # geom_jitter(color = "grey" , alpha = .5) +
  geom_smooth(method = "lm") +
  geom_point(data = data_by_age) +
  # a bit hard to see on this plot if we use labels, suggest we use regular points instead
  # geom_label_repel(data = data_by_age, point.padding = 0, 
        # label.padding = .15, label.size = .1) +
  facet_grid(.~age) + 
  xlab("Adult Judgements") +
  ylab("Kid Judgments") +
  coord_cartesian(ylim = c(1,6), xlim = c(2,6)) +
  scale_y_continuous(breaks = c(1:6)) +
  scale_x_continuous(breaks = c(1:6))
```


### Plot word-level ratings, by age (ordered by AoA)

```{r overall}
ordered_words <- c("dog", "duck", "cat", "pig", "fish", "turtle", "zebra", "elephant", "snake", "penguin", "gorilla", "owl", "raccoon", "leopard", "lobster")

data_by_age_boot <- joined_data %>% 
  mutate(word = factor(word, levels = ordered_words)) %>%
  group_by(age, word, aoa) %>%
  tidyboot_mean(judgment)

ggplot(data_by_age_boot, aes(x = age, y = empirical_stat,
                             ymax = ci_upper, ymin = ci_lower)) + 
  geom_pointrange(size = .25) + 
  facet_wrap(.~word, nrow = 1) +
  xlab("Age") +
  ylab("Knowledge Rating") +
  scale_y_continuous(breaks = c(1:6))
```
  
# Overall Model

```{r model}
model_data <- joined_data %>%
  ungroup() %>%
  mutate(age = scale(as.numeric(age), scale = F),
         aoa_std = scale(aoa),
         judgment_std = scale(judgment))

model <- model_data %>%
  lmer(judgment ~ aoa * age + (1 | id) + (1|word),
       data = .) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  mutate(d = t_to_d(statistic, df)$d,
         d_low = t_to_d(statistic, df)$CI_low,
         d_high = t_to_d(statistic, df)$CI_high) %>%
  select(-effect, -group, -std.error) %>%
  mutate(p.value = printp(p.value))

kable(model)

```

```{r}
summary(lmer(judgment ~ aoa + (1 | id) + (1 | word), data = joined_data %>% filter(age == 4)))
```




#### Individuals but ordered by age (group)

```{r, fig.height = 8, fig.width = 10}
within_age_subj <- joined_data %>%
  group_by(age) %>%
  distinct(id) %>%
  mutate(within_age_subj = seq(n()))

tmp <- left_join(joined_data, within_age_subj, by=c('id', 'age'))
  
tmp %>%
  filter(within_age_subj <= 7) %>%
  ggplot(aes(x = aoa, y = judgment, group = age, color = age,
                      label = word)) + 
  geom_point(aes(alpha = .2)) +
  geom_smooth(method = "lm") + 
  facet_grid(age ~ within_age_subj) +
  ggtitle("Individual Participant's Judgments, by Age") +
  coord_cartesian(ylim= c(0,7)) + 
  theme(legend.position = "none") +
  xlab("Kuperman AoA estimates (adults)") +
  ylab("Kid Judgments") +
  scale_y_continuous(breaks = c(seq(1,6,2)), limit = c(1,6))
```


# Additional Checks

```{r ball-judgment, eval = FALSE}
ggplot(practice_data, aes(x = as.factor(age), y = judgment)) + 
  geom_boxplot() +
  geom_point() +
  labs(x = "age", y = "ball judgment") +
  facet_wrap(~word)
```


```{r}
#12.11.2020 
 # tmp check looking at overall differences in estimating sams knowledge
tmp2 <- joined_data %>%
  #binarize, did they say yes or no
  mutate(known = if_else(judgment >= 4, 1, 0)) %>%
  group_by(age, id) %>%
  count(known) %>%
  group_by(age) %>%
  #how many of the 15 words they think sam knows
  tidyboot_mean(n)

#we don't see any real change in overall number of words they say sam knows
# about 7.5 throughout, more variability with younger kids
ggplot(tmp2, aes(x = age, y = empirical_stat, group = age, ymax = ci_upper, ymin = ci_lower)) + 
  geom_bar(stat = "identity") +
  geom_linerange() +
  xlab("Child Age") +
  ylab("Mean Knowledge Judgment")
```


Estimate correlation between judgments and Kuperman for each age group

```{r age-cor}
age_correlations <- joined_data %>%
  group_by(age, id) %>%
  nest() %>%
  mutate(cor = map(data, ~cor(.x$aoa, .x$judgment, use = "complete"))) %>%
  select(-data) %>%
  unnest(cols = c(cor)) %>%
  group_by(age) %>%
  tidyboot_mean(cor)

kable(age_correlations)

age_correlations %>%
  ggplot(aes(x = age, y = empirical_stat)) +
  geom_point() +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  geom_hline(yintercept = 0, linetype = "dashed")
```



# Explanations

```{r}
explanations <- read_csv("~/Downloads/explanations_code_BM.csv") 
# 1 is location
# 2 is language
# 3 is experience
# 4 is other (+ idks)
# 5 is age/maturation

exp_1 <- read_csv(here("kid_data/explanations_coded_AL.csv"))
exp_1[is.na(exp_1)] <- 0

exp_2 <- read_csv(here("kid_data/explanations_coded-Cass.csv"))
exp_2[is.na(exp_2)] <- 0

explanations <- bind_rows(exp_1, exp_2) %>%
  group_by(ID, why) %>%
  summarise_all(sum)

irr <- explanations %>%
  ungroup %>%
  select(-c(ID, why))

for (i in 1:nrow(irr)) {
  for (j in 1:6){
    if (irr[i,j] == 1) {
      irr[i,j] = 0
    } else if (irr[i,j] == 2) {
      irr[i,j] = 1
    } else {
      irr[i,j] = NA
    }
    }
}

reliability <- irr %>%
  rowMeans(na.rm = T) %>%
  mean()

prop <- exp_1 %>%
  select(-c(ID, why)) %>%
  summarise_all(mean) %>%
  pivot_longer(c(age, experience, language, location, `don't know`, other), 
               names_to = "exp")

ggplot(prop, aes(x = reorder(exp, value), y = value, fill = exp)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x = "Explanation", y = "Proportion")


explanations %>%
  count(as.factor(Code)) %>% mutate(prop = n/sum(n))

joined_with_explanations <- left_join(joined_data, explanations, by = "id")
```

# Overall Effect, by explanation type

```{r, fig.height = 6, fig.width = 9}
data_by_explanation <- joined_with_explanations %>% 
  group_by(Code, word, aoa) %>%
  summarize(judgment = mean(judgment, na.rm=T))

#use the raw data to make line and variability
   #points show averages by Code
ggplot(joined_with_explanations, aes(x = aoa, y = judgment, group = Code,
                      label = word)) +
  geom_point(color = "grey", alpha = .2) +
  geom_smooth(method = "lm") +
  geom_point(data = data_by_explanation) +
  facet_grid(.~Code) + 
  xlab("Kuperman AoA estimates (adults)") +
  ylab("Kid Judgments") +
  coord_cartesian(ylim = c(0,7)) +
  scale_y_continuous(breaks = c(1:6))
```