---
title: "Kid AoA expeirment analysis"
author: "Ashley Leung, Ben Morris, and Dan Yurovsky"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: hide
---

```{r load-libraries, warning = F, message = F}
library(here)
library(knitr)
library(janitor)
library(ggthemes)
library(tidyverse)
library(ggrepel)
library(lme4)
library(lmerTest)
library(broom)
library(broom.mixed)
library(tidyboot)
library(ggthemes)
library(effectsize)
library(papaja)

theme_set(theme_few(base_size = 14))

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)
```

```{r load-data,, warning = F, message = F}
#adjust this total n to grab all the participants data below
n <- 19

pilot_data <- read_csv(here("pilot_data/pilot_data.csv"), col_names = FALSE) %>%
  t() %>%
  as_tibble() %>%
  row_to_names(1) %>%
  clean_names() %>%
  pivot_longer(cols = ball:penguin, names_to = "word", values_to = "judgment") %>%
  mutate(type = if_else(word == "ball", "practice", "test"),
         judgment = as.numeric(judgment)) %>%
  rename(participant = subject_number)

kuperman_aoas <- read_csv(here("corpus_data/kuperman_aoas.csv"))
```


```{r plot-pilot-data}
joined_data <- pilot_data %>%
  left_join(kuperman_aoas, by = "word") %>%
  mutate(age = as.numeric(age)) %>%
  mutate(age_group = case_when(
    age %in% 4:5 ~ "4-5-year-olds",
    age %in% 6:7 ~ "6-7-year-olds",
    age %in% 8:9 ~ "8-9-year-olds",
    age == 10 ~ "older"))

test_data <- joined_data %>%
  filter(type == "test") 

practice_data <- joined_data %>%
  filter(type == "practice")
```

# Overall Effect

```{r overall}
data_overall <- test_data %>% 
  group_by(word, aoa) %>%
  summarize(judgment = mean(judgment, na.rm = T))

ggplot(data_overall, aes(x = aoa, y = judgment,
                      label = word)) + 
  geom_smooth(method = "lm") +
  geom_label_repel() + 
  xlab("Kuperman AoA estimates (adults)") +
  ylab("Kid Judgments")
```

```{r ball-judgment}
ggplot(practice_data, aes(x = as.factor(age), y = judgment)) + 
  geom_boxplot() +
  labs(x = "age", y = "ball judgment")

hard_data <- joined_data %>%
  filter(word %in% c("leopard", "lobster", "raccoon"))

ggplot(hard_data, aes(x = as.factor(age), y = judgment)) + 
  geom_boxplot() +
  labs(x = "age", y = "hardest judgment")
```

# Each participant's judgments

```{r}
test_data %>%
  ggplot(aes(x = aoa, y = judgment,
                      label = word)) + 
  geom_jitter(aes(alpha = .2)) +
  geom_smooth(method = "lm") + 
  facet_wrap( ~ participant)
```


#### Individuals but ordered by age (group)

```{r, fig.height = 8, fig.width = 10}
within_age_subj <- test_data %>%
  group_by(age_group) %>%
  distinct(participant) %>%
  mutate(within_age_subj = seq(n()))

tmp <- left_join(test_data, within_age_subj, by=c('participant', 'age_group'))
  
tmp %>%
  ggplot(aes(x = aoa, y = judgment, group = age_group, color = age_group,
                      label = word)) + 
  geom_point(aes(alpha = .2)) +
  geom_smooth(method = "lm") + 
  facet_grid(age_group ~ within_age_subj) +
  ggtitle("Individual Participant's Judgments, split by age groups") +
  coord_cartesian(ylim= c(0,7)) + 
  theme(legend.position = "none")
```

# Averages by age

```{r, fig.height = 6, fig.width = 9}
data_by_age <- test_data %>% 
  group_by(age, word, aoa) %>%
  summarize(judgment = mean(judgment, na.rm=T))

ggplot(data_by_age, aes(x = aoa, y = judgment, group = age,
                      label = word)) + 
  geom_label_repel() +
  geom_smooth(method = "lm") + 
  facet_grid(.~age)

ggplot(test_data, aes(x = aoa, y = judgment, group = age,
                      label = word)) + 
  geom_smooth(method = "lm",  se = F, aes(group = participant), alpha = .5, color = "grey") + 
  geom_point(color = "grey", alpha = .5) +
  geom_smooth(method = "lm") +
  facet_grid(.~age) +
  coord_cartesian(ylim = c(1,6))
```

Estimate correlation between judgments and Kuperman for each age group
```{r age-cor}
age_correlations <- test_data %>%
  group_by(age, participant) %>%
  nest() %>%
  mutate(cor = map(data, ~cor(.x$aoa, .x$judgment, use = "complete"))) %>%
  select(-data) %>%
  unnest(cols = c(cor)) %>%
  group_by(age) %>%
  tidyboot_mean(cor)

kable(age_correlations)

age_correlations %>%
  ggplot(aes(x = age, y = empirical_stat)) +
  geom_point() +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  geom_hline(yintercept = 0, linetype = "dashed")
```

  
# Overall Model

```{r model}
model_data <- test_data %>%
  filter(age_group != "older") %>%
  mutate(age_group = factor(age_group, 
                           levels = c("4-5-year-olds", "6-7-year-olds", 
                                      "8-9-year-olds")),
         age_group_numeric = as.numeric(age_group) -2 )

model <- model_data %>%
  lmer(judgment ~ aoa * age_group_numeric + (1|participant) + (1|word),
       data = .) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  mutate(d = t_to_d(statistic, df)$d,
         d_low = t_to_d(statistic, df)$CI_low,
         d_high = t_to_d(statistic, df)$CI_high) %>%
  select(-effect, -group, -std.error) %>%
  mutate(p.value = printp(p.value))

kable(model)

```


# Age Models
```{r age-model}
age_model <- model_data %>%
  group_by(age_group) %>%
  nest() %>%
  mutate(model = map(data, ~lmer(judgment ~ aoa + (1|participant) + (1|word),
                                 data = .) %>% tidy())) %>%
  select(-data) %>%
  unnest(cols = c(model)) %>%
  filter(effect == "fixed", term != "(Intercept)") %>%
  mutate(d = t_to_d(statistic, df)$d,
         d_low = t_to_d(statistic, df)$CI_low,
         d_high = t_to_d(statistic, df)$CI_high) %>%
  select(-effect, -group, -std.error, -term) %>%
  mutate(p.value = printp(p.value))

kable(age_model)

```


